2024-12-01 16:54:26,146 : INFO : root : Loading config.
2024-12-01 16:54:26,148 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-12-01 16:54:26,148 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/a187413b8cf7049e0b91852f54cd1afa.mpf_cache
2024-12-01 16:54:26,178 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/2e30198d1c841d95b9b3e69c8a0bb49b.mpf_cache
2024-12-01 16:54:26,178 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/40928215bbb65374348eff3d4cd7b8bc.mpf_cache
2024-12-01 16:54:26,179 : WARNING : ConfigProcessor : Config file in cache changed: /Users/C_Alan/pinball/hauntedhouse/modes/base/config/base.yaml
2024-12-01 16:54:26,179 : INFO : ConfigProcessor : Loading config from file /Users/C_Alan/pinball/hauntedhouse/modes/base/config/base.yaml.
2024-12-01 16:54:26,186 : INFO : ConfigProcessor : Loading config: /Users/C_Alan/pinball/hauntedhouse/modes/base/config/base.yaml
2024-12-01 16:54:26,186 : INFO : ConfigProcessor : Config file cache created: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/167ddff969183ffa73a4682c84ddf638.mpf_cache
2024-12-01 16:54:26,186 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/2e30198d1c841d95b9b3e69c8a0bb49b.mpf_cache
2024-12-01 16:54:26,187 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/f3e7df0542012602a298ddb9f31df321.mpf_cache
2024-12-01 16:54:26,187 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/ac27afd8b01174f1412801db135abc1d.mpf_cache
2024-12-01 16:54:26,187 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/df2857c909c4a913cc732702f1a197bb.mpf_cache
2024-12-01 16:54:26,187 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/1ab5c5e749213b44f20a4087626085fd.mpf_cache
2024-12-01 16:54:26,188 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/176bdc82e0948b16c38e3d140ac1de4b.mpf_cache
2024-12-01 16:54:26,188 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev5
2024-12-01 16:54:26,188 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-12-01-16-54-26-mpf-Macpro.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': '/Users/C_Alan/pinball/hauntedhouse/logs/2024-12-01-16-54-26-mpf-Macpro.local.log'}
2024-12-01 16:54:26,188 : INFO : Machine : MPF path: /Users/C_Alan/envp311/lib/python3.11/site-packages/mpf
2024-12-01 16:54:26,188 : INFO : Machine : Machine path: /Users/C_Alan/pinball/hauntedhouse
2024-12-01 16:54:26,188 : INFO : Machine : Platform: darwin
2024-12-01 16:54:26,188 : INFO : Machine : Python executable location: /Users/C_Alan/envp311/bin/python3.11
2024-12-01 16:54:26,188 : INFO : Machine : Python version: 3.11.0 (64-bit)
2024-12-01 16:54:26,189 : INFO : Machine : Initializing MPF...
2024-12-01 16:54:26,215 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,222 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-12-01 16:54:26,223 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 32800, 'prev_value': None, 'change': True}
2024-12-01 16:54:26,223 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev5', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,223 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev5, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,223 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.0', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,233 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-14.6.1-x86_64-i386-64bit', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,233 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,233 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '23.6.0', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,233 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,233 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,233 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': '/Users/C_Alan/pinball/hauntedhouse/logs/2024-12-01-16-54-26-mpf-Macpro.local.log', 'prev_value': None, 'change': True}
2024-12-01 16:54:26,233 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-12-01 16:54:26,270 : INFO : EventManager : Event: ======'drop_target_bank_upper_up'====== Args={}
2024-12-01 16:54:26,270 : INFO : EventManager : Event: ======'drop_target_bank_lower_up'====== Args={}
2024-12-01 16:54:26,270 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-12-01 16:54:26,276 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2024-12-01 16:54:26,277 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2024-12-01 16:54:30,780 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2024-12-01 16:54:30,781 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2024-12-01 16:54:30,783 : INFO : ball_device.bd_drain : BCH: Initial count: 0
2024-12-01 16:54:30,783 : INFO : ball_device.bd_drain : State: idle
2024-12-01 16:54:30,783 : INFO : ball_device.bd_lower_vuk : BCH: Initial count: 0
2024-12-01 16:54:30,783 : INFO : ball_device.bd_lower_vuk : State: idle
2024-12-01 16:54:30,784 : INFO : ball_device.bd_lower_kickout_special : BCH: Initial count: 0
2024-12-01 16:54:30,784 : INFO : ball_device.bd_lower_kickout_special : State: idle
2024-12-01 16:54:30,784 : INFO : ball_device.bd_main_vuk : BCH: Initial count: 0
2024-12-01 16:54:30,784 : INFO : ball_device.bd_main_vuk : State: idle
2024-12-01 16:54:30,785 : INFO : ball_device.bd_main_kickout_right : BCH: Initial count: 0
2024-12-01 16:54:30,785 : INFO : ball_device.bd_main_kickout_right : State: idle
2024-12-01 16:54:30,785 : INFO : ball_device.bd_main_kickout_lane : BCH: Initial count: 0
2024-12-01 16:54:30,785 : INFO : ball_device.bd_main_kickout_lane : State: idle
2024-12-01 16:54:30,791 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2024-12-01 16:54:30,800 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...ed:" found.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...ed:" found.')>)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/assets/show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/assets/show.py", line 210, in _process_step_actions
    self._show_validation_error('Invalid section "{}:" found.'.format(key), 4)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/assets/show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "flash_trapdoor_light" >> Invalid section "speed:" found. Context: flash_trapdoor_light Error Code: CFE-show-4 (https://missionpinball.org/logs)
2024-12-01 16:54:30,802 : INFO : Machine : Starting the main run loop with active modes: []
2024-12-01 16:54:30,803 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2024-12-01 16:54:30,803 : INFO : Machine : Shutting down...
2024-12-01 16:54:30,803 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-12-01 16:54:31,806 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/assets/show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/assets/show.py", line 210, in _process_step_actions
    self._show_validation_error('Invalid section "{}:" found.'.format(key), 4)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/assets/show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "flash_trapdoor_light" >> Invalid section "speed:" found. Context: flash_trapdoor_light Error Code: CFE-show-4 (https://missionpinball.org/logs)
2024-12-01 16:54:31,807 : INFO : root : MPF run loop ended.
