2024-11-03 10:01:00,626 : INFO : root : Loading config.
2024-11-03 10:01:00,627 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-11-03 10:01:00,627 : INFO : ConfigProcessor : Loading config from cache: /tmp/248da7825a7099821037453685569d45.mpf_cache
2024-11-03 10:01:00,651 : INFO : ConfigProcessor : Loading config from cache: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-03 10:01:00,651 : INFO : ConfigProcessor : Loading config from cache: /tmp/03ef85df1864fb5ef5b7e38cbf9eb8a8.mpf_cache
2024-11-03 10:01:00,651 : INFO : ConfigProcessor : Loading config from cache: /tmp/6dcc9600f5dbf9a99f5346cc5ca34ea9.mpf_cache
2024-11-03 10:01:00,651 : INFO : ConfigProcessor : Loading config from cache: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-03 10:01:00,652 : INFO : ConfigProcessor : Loading config from cache: /tmp/2e5ac6493c6686883ff244e5da957f67.mpf_cache
2024-11-03 10:01:00,652 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev5
2024-11-03 10:01:00,652 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-11-03-10-01-00-mpf-caw-System-Product-Name.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': '/home/caw/pinball/hauntedhouse/logs/2024-11-03-10-01-00-mpf-caw-System-Product-Name.log'}
2024-11-03 10:01:00,652 : INFO : Machine : MPF path: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf
2024-11-03 10:01:00,652 : INFO : Machine : Machine path: /home/caw/pinball/hauntedhouse
2024-11-03 10:01:00,652 : INFO : Machine : Platform: linux
2024-11-03 10:01:00,652 : INFO : Machine : Python executable location: /home/caw/miniconda3/envs/envp311/bin/python
2024-11-03 10:01:00,652 : INFO : Machine : Python version: 3.11.10 (64-bit)
2024-11-03 10:01:00,652 : INFO : Machine : Initializing MPF...
2024-11-03 10:01:00,678 : INFO : P-Roc : Connecting to P-ROC
2024-11-03 10:01:00,684 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 10:01:00,684 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 10:01:01,691 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 10:01:01,691 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 10:01:02,697 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 10:01:02,697 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 10:01:03,704 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 10:01:03,704 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 10:01:04,146 : INFO : Machine : Starting the main run loop with active modes: []
2024-11-03 10:01:04,146 : ERROR : root : 'attract'
Traceback (most recent call last):
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/commands/game.py", line 229, in __init__
    self.machine.run()
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 701, in run
    if not self.modes['attract'] in self.mode_controller.active_modes:
           ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'attract'
